export const USER_VISITED_HOME = 'USER_VISITED_HOME';
export const USER_VISITED_QUESTION = 'USER_VISITED_QUESTION';

export const QUESTIONS_HAVE_LOADED = 'QUESTIONS_HAVE_LOADED';
export const ANSWERS_HAVE_LOADED = 'ANSWERS_HAVE_LOADED';
